-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('MyMessage_pb')


LOGONREQMESSAGE = protobuf.Descriptor();
local LOGONREQMESSAGE_ACCTID_FIELD = protobuf.FieldDescriptor();
local LOGONREQMESSAGE_PASSWD_FIELD = protobuf.FieldDescriptor();

LOGONREQMESSAGE_ACCTID_FIELD.name = "acctID"
LOGONREQMESSAGE_ACCTID_FIELD.full_name = ".net_protocol.LogonReqMessage.acctID"
LOGONREQMESSAGE_ACCTID_FIELD.number = 1
LOGONREQMESSAGE_ACCTID_FIELD.index = 0
LOGONREQMESSAGE_ACCTID_FIELD.label = 2
LOGONREQMESSAGE_ACCTID_FIELD.has_default_value = false
LOGONREQMESSAGE_ACCTID_FIELD.default_value = 0
LOGONREQMESSAGE_ACCTID_FIELD.type = 3
LOGONREQMESSAGE_ACCTID_FIELD.cpp_type = 2

LOGONREQMESSAGE_PASSWD_FIELD.name = "passwd"
LOGONREQMESSAGE_PASSWD_FIELD.full_name = ".net_protocol.LogonReqMessage.passwd"
LOGONREQMESSAGE_PASSWD_FIELD.number = 2
LOGONREQMESSAGE_PASSWD_FIELD.index = 1
LOGONREQMESSAGE_PASSWD_FIELD.label = 2
LOGONREQMESSAGE_PASSWD_FIELD.has_default_value = false
LOGONREQMESSAGE_PASSWD_FIELD.default_value = ""
LOGONREQMESSAGE_PASSWD_FIELD.type = 9
LOGONREQMESSAGE_PASSWD_FIELD.cpp_type = 9

LOGONREQMESSAGE.name = "LogonReqMessage"
LOGONREQMESSAGE.full_name = ".net_protocol.LogonReqMessage"
LOGONREQMESSAGE.nested_types = {}
LOGONREQMESSAGE.enum_types = {}
LOGONREQMESSAGE.fields = {LOGONREQMESSAGE_ACCTID_FIELD, LOGONREQMESSAGE_PASSWD_FIELD}
LOGONREQMESSAGE.is_extendable = false
LOGONREQMESSAGE.extensions = {}

LogonReqMessage = protobuf.Message(LOGONREQMESSAGE)

