-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('ga2gl_pb')


GA2GLROLELOGOUT = protobuf.Descriptor();
local GA2GLROLELOGOUT_GSNETID_FIELD = protobuf.FieldDescriptor();

GA2GLROLELOGOUT_GSNETID_FIELD.name = "gsnetid"
GA2GLROLELOGOUT_GSNETID_FIELD.full_name = ".net_protocol.GA2GLRoleLogout.gsnetid"
GA2GLROLELOGOUT_GSNETID_FIELD.number = 1
GA2GLROLELOGOUT_GSNETID_FIELD.index = 0
GA2GLROLELOGOUT_GSNETID_FIELD.label = 2
GA2GLROLELOGOUT_GSNETID_FIELD.has_default_value = false
GA2GLROLELOGOUT_GSNETID_FIELD.default_value = 0
GA2GLROLELOGOUT_GSNETID_FIELD.type = 13
GA2GLROLELOGOUT_GSNETID_FIELD.cpp_type = 3

GA2GLROLELOGOUT.name = "GA2GLRoleLogout"
GA2GLROLELOGOUT.full_name = ".net_protocol.GA2GLRoleLogout"
GA2GLROLELOGOUT.nested_types = {}
GA2GLROLELOGOUT.enum_types = {}
GA2GLROLELOGOUT.fields = {GA2GLROLELOGOUT_GSNETID_FIELD}
GA2GLROLELOGOUT.is_extendable = false
GA2GLROLELOGOUT.extensions = {}

GA2GLRoleLogout = protobuf.Message(GA2GLROLELOGOUT)

