-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('gl2login_pb')


REQCLIENTLOGOUT = protobuf.Descriptor();
local REQCLIENTLOGOUT_PLAT_NAME_FIELD = protobuf.FieldDescriptor();

REQCLIENTLOGOUT_PLAT_NAME_FIELD.name = "plat_name"
REQCLIENTLOGOUT_PLAT_NAME_FIELD.full_name = ".net_protocol.ReqClientLogout.plat_name"
REQCLIENTLOGOUT_PLAT_NAME_FIELD.number = 1
REQCLIENTLOGOUT_PLAT_NAME_FIELD.index = 0
REQCLIENTLOGOUT_PLAT_NAME_FIELD.label = 2
REQCLIENTLOGOUT_PLAT_NAME_FIELD.has_default_value = false
REQCLIENTLOGOUT_PLAT_NAME_FIELD.default_value = ""
REQCLIENTLOGOUT_PLAT_NAME_FIELD.type = 9
REQCLIENTLOGOUT_PLAT_NAME_FIELD.cpp_type = 9

REQCLIENTLOGOUT.name = "ReqClientLogout"
REQCLIENTLOGOUT.full_name = ".net_protocol.ReqClientLogout"
REQCLIENTLOGOUT.nested_types = {}
REQCLIENTLOGOUT.enum_types = {}
REQCLIENTLOGOUT.fields = {REQCLIENTLOGOUT_PLAT_NAME_FIELD}
REQCLIENTLOGOUT.is_extendable = false
REQCLIENTLOGOUT.extensions = {}

ReqClientLogout = protobuf.Message(REQCLIENTLOGOUT)

