-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('NP_CS_Mail_pb')


C2SMAILGETINFO = protobuf.Descriptor();
C2SMAILGET = protobuf.Descriptor();
local C2SMAILGET_ID_FIELD = protobuf.FieldDescriptor();
C2SMAILGETALL = protobuf.Descriptor();
C2SMAILDELETE = protobuf.Descriptor();
local C2SMAILDELETE_ID_FIELD = protobuf.FieldDescriptor();
C2SMAILSEE = protobuf.Descriptor();
local C2SMAILSEE_ID_FIELD = protobuf.FieldDescriptor();

C2SMAILGETINFO.name = "C2SMailGetInfo"
C2SMAILGETINFO.full_name = ".net_protocol.C2SMailGetInfo"
C2SMAILGETINFO.nested_types = {}
C2SMAILGETINFO.enum_types = {}
C2SMAILGETINFO.fields = {}
C2SMAILGETINFO.is_extendable = false
C2SMAILGETINFO.extensions = {}
C2SMAILGET_ID_FIELD.name = "id"
C2SMAILGET_ID_FIELD.full_name = ".net_protocol.C2SMailGet.id"
C2SMAILGET_ID_FIELD.number = 1
C2SMAILGET_ID_FIELD.index = 0
C2SMAILGET_ID_FIELD.label = 2
C2SMAILGET_ID_FIELD.has_default_value = false
C2SMAILGET_ID_FIELD.default_value = 0
C2SMAILGET_ID_FIELD.type = 13
C2SMAILGET_ID_FIELD.cpp_type = 3

C2SMAILGET.name = "C2SMailGet"
C2SMAILGET.full_name = ".net_protocol.C2SMailGet"
C2SMAILGET.nested_types = {}
C2SMAILGET.enum_types = {}
C2SMAILGET.fields = {C2SMAILGET_ID_FIELD}
C2SMAILGET.is_extendable = false
C2SMAILGET.extensions = {}
C2SMAILGETALL.name = "C2SMailGetAll"
C2SMAILGETALL.full_name = ".net_protocol.C2SMailGetAll"
C2SMAILGETALL.nested_types = {}
C2SMAILGETALL.enum_types = {}
C2SMAILGETALL.fields = {}
C2SMAILGETALL.is_extendable = false
C2SMAILGETALL.extensions = {}
C2SMAILDELETE_ID_FIELD.name = "id"
C2SMAILDELETE_ID_FIELD.full_name = ".net_protocol.C2SMailDelete.id"
C2SMAILDELETE_ID_FIELD.number = 1
C2SMAILDELETE_ID_FIELD.index = 0
C2SMAILDELETE_ID_FIELD.label = 2
C2SMAILDELETE_ID_FIELD.has_default_value = false
C2SMAILDELETE_ID_FIELD.default_value = 0
C2SMAILDELETE_ID_FIELD.type = 13
C2SMAILDELETE_ID_FIELD.cpp_type = 3

C2SMAILDELETE.name = "C2SMailDelete"
C2SMAILDELETE.full_name = ".net_protocol.C2SMailDelete"
C2SMAILDELETE.nested_types = {}
C2SMAILDELETE.enum_types = {}
C2SMAILDELETE.fields = {C2SMAILDELETE_ID_FIELD}
C2SMAILDELETE.is_extendable = false
C2SMAILDELETE.extensions = {}
C2SMAILSEE_ID_FIELD.name = "id"
C2SMAILSEE_ID_FIELD.full_name = ".net_protocol.C2SMailSee.id"
C2SMAILSEE_ID_FIELD.number = 1
C2SMAILSEE_ID_FIELD.index = 0
C2SMAILSEE_ID_FIELD.label = 2
C2SMAILSEE_ID_FIELD.has_default_value = false
C2SMAILSEE_ID_FIELD.default_value = 0
C2SMAILSEE_ID_FIELD.type = 13
C2SMAILSEE_ID_FIELD.cpp_type = 3

C2SMAILSEE.name = "C2SMailSee"
C2SMAILSEE.full_name = ".net_protocol.C2SMailSee"
C2SMAILSEE.nested_types = {}
C2SMAILSEE.enum_types = {}
C2SMAILSEE.fields = {C2SMAILSEE_ID_FIELD}
C2SMAILSEE.is_extendable = false
C2SMAILSEE.extensions = {}

C2SMailDelete = protobuf.Message(C2SMAILDELETE)
C2SMailGet = protobuf.Message(C2SMAILGET)
C2SMailGetAll = protobuf.Message(C2SMAILGETALL)
C2SMailGetInfo = protobuf.Message(C2SMAILGETINFO)
C2SMailSee = protobuf.Message(C2SMAILSEE)

