-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('NP_CS_Treasure_pb')


C2STREASUREGETINFO = protobuf.Descriptor();
C2STREASURELOTTERY = protobuf.Descriptor();
local C2STREASURELOTTERY_TYPE_FIELD = protobuf.FieldDescriptor();

C2STREASUREGETINFO.name = "C2STreasureGetInfo"
C2STREASUREGETINFO.full_name = ".net_protocol.C2STreasureGetInfo"
C2STREASUREGETINFO.nested_types = {}
C2STREASUREGETINFO.enum_types = {}
C2STREASUREGETINFO.fields = {}
C2STREASUREGETINFO.is_extendable = false
C2STREASUREGETINFO.extensions = {}
C2STREASURELOTTERY_TYPE_FIELD.name = "type"
C2STREASURELOTTERY_TYPE_FIELD.full_name = ".net_protocol.C2STreasureLottery.type"
C2STREASURELOTTERY_TYPE_FIELD.number = 1
C2STREASURELOTTERY_TYPE_FIELD.index = 0
C2STREASURELOTTERY_TYPE_FIELD.label = 2
C2STREASURELOTTERY_TYPE_FIELD.has_default_value = false
C2STREASURELOTTERY_TYPE_FIELD.default_value = 0
C2STREASURELOTTERY_TYPE_FIELD.type = 13
C2STREASURELOTTERY_TYPE_FIELD.cpp_type = 3

C2STREASURELOTTERY.name = "C2STreasureLottery"
C2STREASURELOTTERY.full_name = ".net_protocol.C2STreasureLottery"
C2STREASURELOTTERY.nested_types = {}
C2STREASURELOTTERY.enum_types = {}
C2STREASURELOTTERY.fields = {C2STREASURELOTTERY_TYPE_FIELD}
C2STREASURELOTTERY.is_extendable = false
C2STREASURELOTTERY.extensions = {}

C2STreasureGetInfo = protobuf.Message(C2STREASUREGETINFO)
C2STreasureLottery = protobuf.Message(C2STREASURELOTTERY)

