-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('NP_CS_Gm_pb')


C2SREQGMCMD = protobuf.Descriptor();
local C2SREQGMCMD_CMD_FIELD = protobuf.FieldDescriptor();

C2SREQGMCMD_CMD_FIELD.name = "cmd"
C2SREQGMCMD_CMD_FIELD.full_name = ".net_protocol.C2SReqGmCmd.cmd"
C2SREQGMCMD_CMD_FIELD.number = 1
C2SREQGMCMD_CMD_FIELD.index = 0
C2SREQGMCMD_CMD_FIELD.label = 2
C2SREQGMCMD_CMD_FIELD.has_default_value = false
C2SREQGMCMD_CMD_FIELD.default_value = ""
C2SREQGMCMD_CMD_FIELD.type = 9
C2SREQGMCMD_CMD_FIELD.cpp_type = 9

C2SREQGMCMD.name = "C2SReqGmCmd"
C2SREQGMCMD.full_name = ".net_protocol.C2SReqGmCmd"
C2SREQGMCMD.nested_types = {}
C2SREQGMCMD.enum_types = {}
C2SREQGMCMD.fields = {C2SREQGMCMD_CMD_FIELD}
C2SREQGMCMD.is_extendable = false
C2SREQGMCMD.extensions = {}

C2SReqGmCmd = protobuf.Message(C2SREQGMCMD)

