-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('NP_CS_Notice_pb')


C2SNOTICEGETINFO = protobuf.Descriptor();

C2SNOTICEGETINFO.name = "C2SNoticeGetInfo"
C2SNOTICEGETINFO.full_name = ".net_protocol.C2SNoticeGetInfo"
C2SNOTICEGETINFO.nested_types = {}
C2SNOTICEGETINFO.enum_types = {}
C2SNOTICEGETINFO.fields = {}
C2SNOTICEGETINFO.is_extendable = false
C2SNOTICEGETINFO.extensions = {}

C2SNoticeGetInfo = protobuf.Message(C2SNOTICEGETINFO)

