-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('NP_CS_Bag_pb')


C2SBAGGETINFO = protobuf.Descriptor();
C2SBAGUSEITEM = protobuf.Descriptor();
local C2SBAGUSEITEM_ID_FIELD = protobuf.FieldDescriptor();
local C2SBAGUSEITEM_NUM_FIELD = protobuf.FieldDescriptor();
C2SBAGSELLITEM = protobuf.Descriptor();
local C2SBAGSELLITEM_ID_FIELD = protobuf.FieldDescriptor();
local C2SBAGSELLITEM_NUM_FIELD = protobuf.FieldDescriptor();

C2SBAGGETINFO.name = "C2SBagGetInfo"
C2SBAGGETINFO.full_name = ".net_protocol.C2SBagGetInfo"
C2SBAGGETINFO.nested_types = {}
C2SBAGGETINFO.enum_types = {}
C2SBAGGETINFO.fields = {}
C2SBAGGETINFO.is_extendable = false
C2SBAGGETINFO.extensions = {}
C2SBAGUSEITEM_ID_FIELD.name = "id"
C2SBAGUSEITEM_ID_FIELD.full_name = ".net_protocol.C2SBagUseItem.id"
C2SBAGUSEITEM_ID_FIELD.number = 1
C2SBAGUSEITEM_ID_FIELD.index = 0
C2SBAGUSEITEM_ID_FIELD.label = 2
C2SBAGUSEITEM_ID_FIELD.has_default_value = false
C2SBAGUSEITEM_ID_FIELD.default_value = 0
C2SBAGUSEITEM_ID_FIELD.type = 13
C2SBAGUSEITEM_ID_FIELD.cpp_type = 3

C2SBAGUSEITEM_NUM_FIELD.name = "num"
C2SBAGUSEITEM_NUM_FIELD.full_name = ".net_protocol.C2SBagUseItem.num"
C2SBAGUSEITEM_NUM_FIELD.number = 2
C2SBAGUSEITEM_NUM_FIELD.index = 1
C2SBAGUSEITEM_NUM_FIELD.label = 2
C2SBAGUSEITEM_NUM_FIELD.has_default_value = false
C2SBAGUSEITEM_NUM_FIELD.default_value = 0
C2SBAGUSEITEM_NUM_FIELD.type = 13
C2SBAGUSEITEM_NUM_FIELD.cpp_type = 3

C2SBAGUSEITEM.name = "C2SBagUseItem"
C2SBAGUSEITEM.full_name = ".net_protocol.C2SBagUseItem"
C2SBAGUSEITEM.nested_types = {}
C2SBAGUSEITEM.enum_types = {}
C2SBAGUSEITEM.fields = {C2SBAGUSEITEM_ID_FIELD, C2SBAGUSEITEM_NUM_FIELD}
C2SBAGUSEITEM.is_extendable = false
C2SBAGUSEITEM.extensions = {}
C2SBAGSELLITEM_ID_FIELD.name = "id"
C2SBAGSELLITEM_ID_FIELD.full_name = ".net_protocol.C2SBagSellItem.id"
C2SBAGSELLITEM_ID_FIELD.number = 1
C2SBAGSELLITEM_ID_FIELD.index = 0
C2SBAGSELLITEM_ID_FIELD.label = 2
C2SBAGSELLITEM_ID_FIELD.has_default_value = false
C2SBAGSELLITEM_ID_FIELD.default_value = 0
C2SBAGSELLITEM_ID_FIELD.type = 13
C2SBAGSELLITEM_ID_FIELD.cpp_type = 3

C2SBAGSELLITEM_NUM_FIELD.name = "num"
C2SBAGSELLITEM_NUM_FIELD.full_name = ".net_protocol.C2SBagSellItem.num"
C2SBAGSELLITEM_NUM_FIELD.number = 2
C2SBAGSELLITEM_NUM_FIELD.index = 1
C2SBAGSELLITEM_NUM_FIELD.label = 2
C2SBAGSELLITEM_NUM_FIELD.has_default_value = false
C2SBAGSELLITEM_NUM_FIELD.default_value = 0
C2SBAGSELLITEM_NUM_FIELD.type = 13
C2SBAGSELLITEM_NUM_FIELD.cpp_type = 3

C2SBAGSELLITEM.name = "C2SBagSellItem"
C2SBAGSELLITEM.full_name = ".net_protocol.C2SBagSellItem"
C2SBAGSELLITEM.nested_types = {}
C2SBAGSELLITEM.enum_types = {}
C2SBAGSELLITEM.fields = {C2SBAGSELLITEM_ID_FIELD, C2SBAGSELLITEM_NUM_FIELD}
C2SBAGSELLITEM.is_extendable = false
C2SBAGSELLITEM.extensions = {}

C2SBagGetInfo = protobuf.Message(C2SBAGGETINFO)
C2SBagSellItem = protobuf.Message(C2SBAGSELLITEM)
C2SBagUseItem = protobuf.Message(C2SBAGUSEITEM)

