-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('NP_CS_Rank_pb')


C2SRANKGETINFO = protobuf.Descriptor();

C2SRANKGETINFO.name = "C2SRankGetInfo"
C2SRANKGETINFO.full_name = ".net_protocol.C2SRankGetInfo"
C2SRANKGETINFO.nested_types = {}
C2SRANKGETINFO.enum_types = {}
C2SRANKGETINFO.fields = {}
C2SRANKGETINFO.is_extendable = false
C2SRANKGETINFO.extensions = {}

C2SRankGetInfo = protobuf.Message(C2SRANKGETINFO)

