-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('NP_SC_Rank_pb')


BASE = protobuf.Descriptor();
local BASE_RANK_FIELD = protobuf.FieldDescriptor();
local BASE_HEAD_ID_FIELD = protobuf.FieldDescriptor();
local BASE_VIP_LEVEL_FIELD = protobuf.FieldDescriptor();
local BASE_NAME_FIELD = protobuf.FieldDescriptor();
local BASE_SCORE_FIELD = protobuf.FieldDescriptor();
local BASE_USER_NAME_FIELD = protobuf.FieldDescriptor();
RANK_LIST = protobuf.Descriptor();
local RANK_LIST_TYPE_FIELD = protobuf.FieldDescriptor();
local RANK_LIST_RANK_FIELD = protobuf.FieldDescriptor();
local RANK_LIST_OWN_FIELD = protobuf.FieldDescriptor();
S2CRANKGETINFO = protobuf.Descriptor();
local S2CRANKGETINFO_INFO_FIELD = protobuf.FieldDescriptor();

BASE_RANK_FIELD.name = "rank"
BASE_RANK_FIELD.full_name = ".net_protocol.base.rank"
BASE_RANK_FIELD.number = 1
BASE_RANK_FIELD.index = 0
BASE_RANK_FIELD.label = 2
BASE_RANK_FIELD.has_default_value = false
BASE_RANK_FIELD.default_value = 0
BASE_RANK_FIELD.type = 13
BASE_RANK_FIELD.cpp_type = 3

BASE_HEAD_ID_FIELD.name = "head_id"
BASE_HEAD_ID_FIELD.full_name = ".net_protocol.base.head_id"
BASE_HEAD_ID_FIELD.number = 2
BASE_HEAD_ID_FIELD.index = 1
BASE_HEAD_ID_FIELD.label = 2
BASE_HEAD_ID_FIELD.has_default_value = false
BASE_HEAD_ID_FIELD.default_value = 0
BASE_HEAD_ID_FIELD.type = 13
BASE_HEAD_ID_FIELD.cpp_type = 3

BASE_VIP_LEVEL_FIELD.name = "vip_level"
BASE_VIP_LEVEL_FIELD.full_name = ".net_protocol.base.vip_level"
BASE_VIP_LEVEL_FIELD.number = 3
BASE_VIP_LEVEL_FIELD.index = 2
BASE_VIP_LEVEL_FIELD.label = 2
BASE_VIP_LEVEL_FIELD.has_default_value = false
BASE_VIP_LEVEL_FIELD.default_value = 0
BASE_VIP_LEVEL_FIELD.type = 13
BASE_VIP_LEVEL_FIELD.cpp_type = 3

BASE_NAME_FIELD.name = "name"
BASE_NAME_FIELD.full_name = ".net_protocol.base.name"
BASE_NAME_FIELD.number = 4
BASE_NAME_FIELD.index = 3
BASE_NAME_FIELD.label = 2
BASE_NAME_FIELD.has_default_value = false
BASE_NAME_FIELD.default_value = ""
BASE_NAME_FIELD.type = 9
BASE_NAME_FIELD.cpp_type = 9

BASE_SCORE_FIELD.name = "score"
BASE_SCORE_FIELD.full_name = ".net_protocol.base.score"
BASE_SCORE_FIELD.number = 5
BASE_SCORE_FIELD.index = 4
BASE_SCORE_FIELD.label = 2
BASE_SCORE_FIELD.has_default_value = false
BASE_SCORE_FIELD.default_value = 0
BASE_SCORE_FIELD.type = 13
BASE_SCORE_FIELD.cpp_type = 3

BASE_USER_NAME_FIELD.name = "user_name"
BASE_USER_NAME_FIELD.full_name = ".net_protocol.base.user_name"
BASE_USER_NAME_FIELD.number = 6
BASE_USER_NAME_FIELD.index = 5
BASE_USER_NAME_FIELD.label = 2
BASE_USER_NAME_FIELD.has_default_value = false
BASE_USER_NAME_FIELD.default_value = ""
BASE_USER_NAME_FIELD.type = 9
BASE_USER_NAME_FIELD.cpp_type = 9

BASE.name = "base"
BASE.full_name = ".net_protocol.base"
BASE.nested_types = {}
BASE.enum_types = {}
BASE.fields = {BASE_RANK_FIELD, BASE_HEAD_ID_FIELD, BASE_VIP_LEVEL_FIELD, BASE_NAME_FIELD, BASE_SCORE_FIELD, BASE_USER_NAME_FIELD}
BASE.is_extendable = false
BASE.extensions = {}
RANK_LIST_TYPE_FIELD.name = "type"
RANK_LIST_TYPE_FIELD.full_name = ".net_protocol.rank_list.type"
RANK_LIST_TYPE_FIELD.number = 1
RANK_LIST_TYPE_FIELD.index = 0
RANK_LIST_TYPE_FIELD.label = 2
RANK_LIST_TYPE_FIELD.has_default_value = false
RANK_LIST_TYPE_FIELD.default_value = 0
RANK_LIST_TYPE_FIELD.type = 13
RANK_LIST_TYPE_FIELD.cpp_type = 3

RANK_LIST_RANK_FIELD.name = "rank"
RANK_LIST_RANK_FIELD.full_name = ".net_protocol.rank_list.rank"
RANK_LIST_RANK_FIELD.number = 2
RANK_LIST_RANK_FIELD.index = 1
RANK_LIST_RANK_FIELD.label = 3
RANK_LIST_RANK_FIELD.has_default_value = false
RANK_LIST_RANK_FIELD.default_value = {}
RANK_LIST_RANK_FIELD.message_type = BASE
RANK_LIST_RANK_FIELD.type = 11
RANK_LIST_RANK_FIELD.cpp_type = 10

RANK_LIST_OWN_FIELD.name = "own"
RANK_LIST_OWN_FIELD.full_name = ".net_protocol.rank_list.own"
RANK_LIST_OWN_FIELD.number = 3
RANK_LIST_OWN_FIELD.index = 2
RANK_LIST_OWN_FIELD.label = 2
RANK_LIST_OWN_FIELD.has_default_value = false
RANK_LIST_OWN_FIELD.default_value = 0
RANK_LIST_OWN_FIELD.type = 13
RANK_LIST_OWN_FIELD.cpp_type = 3

RANK_LIST.name = "rank_list"
RANK_LIST.full_name = ".net_protocol.rank_list"
RANK_LIST.nested_types = {}
RANK_LIST.enum_types = {}
RANK_LIST.fields = {RANK_LIST_TYPE_FIELD, RANK_LIST_RANK_FIELD, RANK_LIST_OWN_FIELD}
RANK_LIST.is_extendable = false
RANK_LIST.extensions = {}
S2CRANKGETINFO_INFO_FIELD.name = "info"
S2CRANKGETINFO_INFO_FIELD.full_name = ".net_protocol.S2CRankGetInfo.info"
S2CRANKGETINFO_INFO_FIELD.number = 1
S2CRANKGETINFO_INFO_FIELD.index = 0
S2CRANKGETINFO_INFO_FIELD.label = 3
S2CRANKGETINFO_INFO_FIELD.has_default_value = false
S2CRANKGETINFO_INFO_FIELD.default_value = {}
S2CRANKGETINFO_INFO_FIELD.message_type = RANK_LIST
S2CRANKGETINFO_INFO_FIELD.type = 11
S2CRANKGETINFO_INFO_FIELD.cpp_type = 10

S2CRANKGETINFO.name = "S2CRankGetInfo"
S2CRANKGETINFO.full_name = ".net_protocol.S2CRankGetInfo"
S2CRANKGETINFO.nested_types = {}
S2CRANKGETINFO.enum_types = {}
S2CRANKGETINFO.fields = {S2CRANKGETINFO_INFO_FIELD}
S2CRANKGETINFO.is_extendable = false
S2CRANKGETINFO.extensions = {}

S2CRankGetInfo = protobuf.Message(S2CRANKGETINFO)
base = protobuf.Message(BASE)
rank_list = protobuf.Message(RANK_LIST)

