-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('NP_SC_Notice_pb')


NOTICE = protobuf.Descriptor();
local NOTICE_ID_FIELD = protobuf.FieldDescriptor();
local NOTICE_TYPE_FIELD = protobuf.FieldDescriptor();
local NOTICE_CONTENT_FIELD = protobuf.FieldDescriptor();
local NOTICE_POP_FIELD = protobuf.FieldDescriptor();
S2CNOTICEGETINFO = protobuf.Descriptor();
local S2CNOTICEGETINFO_INFO_FIELD = protobuf.FieldDescriptor();

NOTICE_ID_FIELD.name = "id"
NOTICE_ID_FIELD.full_name = ".net_protocol.notice.id"
NOTICE_ID_FIELD.number = 1
NOTICE_ID_FIELD.index = 0
NOTICE_ID_FIELD.label = 2
NOTICE_ID_FIELD.has_default_value = false
NOTICE_ID_FIELD.default_value = 0
NOTICE_ID_FIELD.type = 13
NOTICE_ID_FIELD.cpp_type = 3

NOTICE_TYPE_FIELD.name = "type"
NOTICE_TYPE_FIELD.full_name = ".net_protocol.notice.type"
NOTICE_TYPE_FIELD.number = 2
NOTICE_TYPE_FIELD.index = 1
NOTICE_TYPE_FIELD.label = 2
NOTICE_TYPE_FIELD.has_default_value = false
NOTICE_TYPE_FIELD.default_value = 0
NOTICE_TYPE_FIELD.type = 13
NOTICE_TYPE_FIELD.cpp_type = 3

NOTICE_CONTENT_FIELD.name = "content"
NOTICE_CONTENT_FIELD.full_name = ".net_protocol.notice.content"
NOTICE_CONTENT_FIELD.number = 3
NOTICE_CONTENT_FIELD.index = 2
NOTICE_CONTENT_FIELD.label = 2
NOTICE_CONTENT_FIELD.has_default_value = false
NOTICE_CONTENT_FIELD.default_value = ""
NOTICE_CONTENT_FIELD.type = 9
NOTICE_CONTENT_FIELD.cpp_type = 9

NOTICE_POP_FIELD.name = "pop"
NOTICE_POP_FIELD.full_name = ".net_protocol.notice.pop"
NOTICE_POP_FIELD.number = 4
NOTICE_POP_FIELD.index = 3
NOTICE_POP_FIELD.label = 2
NOTICE_POP_FIELD.has_default_value = false
NOTICE_POP_FIELD.default_value = 0
NOTICE_POP_FIELD.type = 13
NOTICE_POP_FIELD.cpp_type = 3

NOTICE.name = "notice"
NOTICE.full_name = ".net_protocol.notice"
NOTICE.nested_types = {}
NOTICE.enum_types = {}
NOTICE.fields = {NOTICE_ID_FIELD, NOTICE_TYPE_FIELD, NOTICE_CONTENT_FIELD, NOTICE_POP_FIELD}
NOTICE.is_extendable = false
NOTICE.extensions = {}
S2CNOTICEGETINFO_INFO_FIELD.name = "info"
S2CNOTICEGETINFO_INFO_FIELD.full_name = ".net_protocol.S2CNoticeGetInfo.info"
S2CNOTICEGETINFO_INFO_FIELD.number = 1
S2CNOTICEGETINFO_INFO_FIELD.index = 0
S2CNOTICEGETINFO_INFO_FIELD.label = 3
S2CNOTICEGETINFO_INFO_FIELD.has_default_value = false
S2CNOTICEGETINFO_INFO_FIELD.default_value = {}
S2CNOTICEGETINFO_INFO_FIELD.message_type = NOTICE
S2CNOTICEGETINFO_INFO_FIELD.type = 11
S2CNOTICEGETINFO_INFO_FIELD.cpp_type = 10

S2CNOTICEGETINFO.name = "S2CNoticeGetInfo"
S2CNOTICEGETINFO.full_name = ".net_protocol.S2CNoticeGetInfo"
S2CNOTICEGETINFO.nested_types = {}
S2CNOTICEGETINFO.enum_types = {}
S2CNOTICEGETINFO.fields = {S2CNOTICEGETINFO_INFO_FIELD}
S2CNOTICEGETINFO.is_extendable = false
S2CNOTICEGETINFO.extensions = {}

S2CNoticeGetInfo = protobuf.Message(S2CNOTICEGETINFO)
notice = protobuf.Message(NOTICE)

