// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyMessage.proto

#ifndef PROTOBUF_MyMessage_2eproto__INCLUDED
#define PROTOBUF_MyMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace net_protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MyMessage_2eproto();
void protobuf_AssignDesc_MyMessage_2eproto();
void protobuf_ShutdownFile_MyMessage_2eproto();

class LogonReqMessage;

// ===================================================================

class LogonReqMessage : public ::google::protobuf::Message {
 public:
  LogonReqMessage();
  virtual ~LogonReqMessage();

  LogonReqMessage(const LogonReqMessage& from);

  inline LogonReqMessage& operator=(const LogonReqMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LogonReqMessage& default_instance();

  void Swap(LogonReqMessage* other);

  // implements Message ----------------------------------------------

  LogonReqMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LogonReqMessage& from);
  void MergeFrom(const LogonReqMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 acctID = 1;
  inline bool has_acctid() const;
  inline void clear_acctid();
  static const int kAcctIDFieldNumber = 1;
  inline ::google::protobuf::int64 acctid() const;
  inline void set_acctid(::google::protobuf::int64 value);

  // required string passwd = 2;
  inline bool has_passwd() const;
  inline void clear_passwd();
  static const int kPasswdFieldNumber = 2;
  inline const ::std::string& passwd() const;
  inline void set_passwd(const ::std::string& value);
  inline void set_passwd(const char* value);
  inline void set_passwd(const char* value, size_t size);
  inline ::std::string* mutable_passwd();
  inline ::std::string* release_passwd();
  inline void set_allocated_passwd(::std::string* passwd);

  // @@protoc_insertion_point(class_scope:net_protocol.LogonReqMessage)
 private:
  inline void set_has_acctid();
  inline void clear_has_acctid();
  inline void set_has_passwd();
  inline void clear_has_passwd();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 acctid_;
  ::std::string* passwd_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_MyMessage_2eproto();
  friend void protobuf_AssignDesc_MyMessage_2eproto();
  friend void protobuf_ShutdownFile_MyMessage_2eproto();

  void InitAsDefaultInstance();
  static LogonReqMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// LogonReqMessage

// required int64 acctID = 1;
inline bool LogonReqMessage::has_acctid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LogonReqMessage::set_has_acctid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LogonReqMessage::clear_has_acctid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LogonReqMessage::clear_acctid() {
  acctid_ = GOOGLE_LONGLONG(0);
  clear_has_acctid();
}
inline ::google::protobuf::int64 LogonReqMessage::acctid() const {
  return acctid_;
}
inline void LogonReqMessage::set_acctid(::google::protobuf::int64 value) {
  set_has_acctid();
  acctid_ = value;
}

// required string passwd = 2;
inline bool LogonReqMessage::has_passwd() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LogonReqMessage::set_has_passwd() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LogonReqMessage::clear_has_passwd() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LogonReqMessage::clear_passwd() {
  if (passwd_ != &::google::protobuf::internal::kEmptyString) {
    passwd_->clear();
  }
  clear_has_passwd();
}
inline const ::std::string& LogonReqMessage::passwd() const {
  return *passwd_;
}
inline void LogonReqMessage::set_passwd(const ::std::string& value) {
  set_has_passwd();
  if (passwd_ == &::google::protobuf::internal::kEmptyString) {
    passwd_ = new ::std::string;
  }
  passwd_->assign(value);
}
inline void LogonReqMessage::set_passwd(const char* value) {
  set_has_passwd();
  if (passwd_ == &::google::protobuf::internal::kEmptyString) {
    passwd_ = new ::std::string;
  }
  passwd_->assign(value);
}
inline void LogonReqMessage::set_passwd(const char* value, size_t size) {
  set_has_passwd();
  if (passwd_ == &::google::protobuf::internal::kEmptyString) {
    passwd_ = new ::std::string;
  }
  passwd_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* LogonReqMessage::mutable_passwd() {
  set_has_passwd();
  if (passwd_ == &::google::protobuf::internal::kEmptyString) {
    passwd_ = new ::std::string;
  }
  return passwd_;
}
inline ::std::string* LogonReqMessage::release_passwd() {
  clear_has_passwd();
  if (passwd_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = passwd_;
    passwd_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void LogonReqMessage::set_allocated_passwd(::std::string* passwd) {
  if (passwd_ != &::google::protobuf::internal::kEmptyString) {
    delete passwd_;
  }
  if (passwd) {
    set_has_passwd();
    passwd_ = passwd;
  } else {
    clear_has_passwd();
    passwd_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace net_protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MyMessage_2eproto__INCLUDED
